### ISSUE TITLE
Rerouting 

### ISSUE THREAD

**Issue by ematipico** [snowpackjs/rfcs#896]
- Accepted Date: 2024-04-16
- Reference Issues/Discussions: https://github.com/withastro/roadmap/discussions/681
- Author: @lilnasy 
- Champion(s): @ematipico @lilnasy 
- Implementation PR: 

# Summary

Programmatic control over routing.

# Background & Motivation

As astro grows in popularity, it is being used for more and more use cases. One of these is multitenant websites where a tenant may be given a subdomain. This proposal introduces a powerful primitive that allows astro users to build websites with complex routing requirements. Rather than a limitation, file-based routing is now a sensible default!

# Goals

- Defuse.
- Make it unnecessary to rely on implicit routing rules
- Introduce framework-designed 404 and 500 pages 
- Make middleware run for requests that don't match a route (with framework-designed error pages)

# Non-Goals 

- Reroute to an external service.
- Support for `functionPerRoute`

**Comment by florian-lefebvre** [comment]
Stage 3 RFC available in #901
